package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 25/10/2015 10:09:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Analisismedico generated by Gian
 */
public class Analisismedico implements java.io.Serializable {

	private Integer idAnalisisMedico;
	private Atencionmedica atencionmedica;
	private Tipoanalisis tipoanalisis;
	private Clinicoveterinario clinicoveterinario;
	private Set detalleanalisises = new HashSet(0);

	public Analisismedico() {
	}

	public Analisismedico(Atencionmedica atencionmedica, Tipoanalisis tipoanalisis,
			Clinicoveterinario clinicoveterinario) {
		this.atencionmedica = atencionmedica;
		this.tipoanalisis = tipoanalisis;
		this.clinicoveterinario = clinicoveterinario;
	}

	public Analisismedico(Atencionmedica atencionmedica, Tipoanalisis tipoanalisis,
			Clinicoveterinario clinicoveterinario, Set detalleanalisises) {
		this.atencionmedica = atencionmedica;
		this.tipoanalisis = tipoanalisis;
		this.clinicoveterinario = clinicoveterinario;
		this.detalleanalisises = detalleanalisises;
	}

	public Integer getIdAnalisisMedico() {
		return this.idAnalisisMedico;
	}

	public void setIdAnalisisMedico(Integer idAnalisisMedico) {
		this.idAnalisisMedico = idAnalisisMedico;
	}

	public Atencionmedica getAtencionmedica() {
		return this.atencionmedica;
	}

	public void setAtencionmedica(Atencionmedica atencionmedica) {
		this.atencionmedica = atencionmedica;
	}

	public Tipoanalisis getTipoanalisis() {
		return this.tipoanalisis;
	}

	public void setTipoanalisis(Tipoanalisis tipoanalisis) {
		this.tipoanalisis = tipoanalisis;
	}

	public Clinicoveterinario getClinicoveterinario() {
		return this.clinicoveterinario;
	}

	public void setClinicoveterinario(Clinicoveterinario clinicoveterinario) {
		this.clinicoveterinario = clinicoveterinario;
	}

	public Set getDetalleanalisises() {
		return this.detalleanalisises;
	}

	public void setDetalleanalisises(Set detalleanalisises) {
		this.detalleanalisises = detalleanalisises;
	}

}
