package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 25/10/2015 10:09:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Detalleanalisis generated by hbm2java
 */
public class Detalleanalisis implements java.io.Serializable {

	private Integer idDetalleAnalisis;
	private Analisismedico analisismedico;

	public Detalleanalisis() {
	}

	public Detalleanalisis(Analisismedico analisismedico) {
		this.analisismedico = analisismedico;
	}

	public Integer getIdDetalleAnalisis() {
		return this.idDetalleAnalisis;
	}

	public void setIdDetalleAnalisis(Integer idDetalleAnalisis) {
		this.idDetalleAnalisis = idDetalleAnalisis;
	}

	public Analisismedico getAnalisismedico() {
		return this.analisismedico;
	}

	public void setAnalisismedico(Analisismedico analisismedico) {
		this.analisismedico = analisismedico;
	}

}
