package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 25/10/2015 10:09:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Estadoatencionmedica generated by hbm2java
 */
public class Estadoatencionmedica implements java.io.Serializable {

	private Integer idEstadoAtencionMedica;
	private String estado;
	private Set atencionmedicas = new HashSet(0);

	public Estadoatencionmedica() {
	}

	public Estadoatencionmedica(String estado, Set atencionmedicas) {
		this.estado = estado;
		this.atencionmedicas = atencionmedicas;
	}

	public Integer getIdEstadoAtencionMedica() {
		return this.idEstadoAtencionMedica;
	}

	public void setIdEstadoAtencionMedica(Integer idEstadoAtencionMedica) {
		this.idEstadoAtencionMedica = idEstadoAtencionMedica;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getAtencionmedicas() {
		return this.atencionmedicas;
	}

	public void setAtencionmedicas(Set atencionmedicas) {
		this.atencionmedicas = atencionmedicas;
	}

}
