package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 21/09/2015 09:52:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * Historial generated by hbm2java
 */
public class Historial implements java.io.Serializable {

	private Integer idHistorial;
	private Paciente paciente;

	public Historial() {
	}

	public Historial(Paciente paciente) {
		this.paciente = paciente;
	}

	public Integer getIdHistorial() {
		return this.idHistorial;
	}

	public void setIdHistorial(Integer idHistorial) {
		this.idHistorial = idHistorial;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

}
