package pe.edu.unmsm.veterinaria.clinica.entities;
// Generated 25/10/2015 10:09:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Receta generated by hbm2java
 */
public class Receta implements java.io.Serializable {

	private Integer idReceta;
	private Atencionmedica atencionmedica;

	public Receta() {
	}

	public Receta(Atencionmedica atencionmedica) {
		this.atencionmedica = atencionmedica;
	}

	public Integer getIdReceta() {
		return this.idReceta;
	}

	public void setIdReceta(Integer idReceta) {
		this.idReceta = idReceta;
	}

	public Atencionmedica getAtencionmedica() {
		return this.atencionmedica;
	}

	public void setAtencionmedica(Atencionmedica atencionmedica) {
		this.atencionmedica = atencionmedica;
	}

}
